version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - backend
    networks:
      - front-tier
    command: ["sh", "-c", "./wait-for-it.sh -t 10 backend:3000 --strict -- nginx -g \"daemon off;\""]

  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: on-failure
    depends_on:
      - database
    networks:
      - front-tier
      - back-tier
    volumes:
      - upload-data-volume:/usr/src/app/upload
    command: ["sh", "-c", "./wait-for-postgres.sh database ./docker-entrypoint.sh"]

  database:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: on-failure
    networks:
      - back-tier
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  postgres-data-volume:
  upload-data-volume:
