version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: transpong
      POSTGRES_PASSWORD: transpong
      POSTGRES_DB: transpong
      TZ: Asia/Tokyo
    restart: always
    networks:
      - mynetwork
networks:
  mynetwork:
