
name: labeled2

on:
  pull_request_target:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    steps:
      - name: hellohellohello
        run: echo HelloHelloHello
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: echo dummy
        run:  cat dummy.txt
      - name: git log
        run: git log
